# docker-compose.yml
# recal
# Author: Rushy Panchal
# Date: November 27th, 2017
# Description: Docker compose configuration.

version: '3.3'
services:
  db:
    image: postgres:9.6.2
    ports:
      - 5432

  web:
    env_file: .compose-env
    build:
      context: .
      args:
        - PORT=5000
    ports:
      - 5000
    links:
      - db
    restart: always
