# docker-compose.yml
# recal
# Author: Rushy Panchal
# Date: April 4th, 2017
# Description: Docker compose configuration.

version: '3.3'
services:
  db:
    image: postgres:9.6.2
    ports:
      - 5432

  web:
    build:
      context: .
      args:
        PORT: 5000
    command: gunicorn course_selection.wsgi:application
    environment:
      - PORT=5000
      - DOCKER_COMPOSE=1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/recal
      - PDFTK_BIN=/usr/local/bin/pdftk
      - DJANGO_DEBUG=1
      - ALLOWED_HOSTS=localhost
    ports:
      - 5000:5000
    links:
      - db
    restart: always
